name: Deploy

on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/**", "backend/**" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
      env:
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        SOLVANN_USERNAME: ${{secrets.SOLVANN_USERNAME}}
        SOLVANN_PASSWORD: ${{secrets.SOLVANN_PASSWORD}}
  
  build-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: ""
    - run: npm test
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend
        path: frontend/build
        if-no-files-found: error
        retention-days: 1


  deploy-backend:
    needs: [test-backend]
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy backend
      uses: sand4rt/ftp-deployer@v1.7
      with:
        sftp: true
        host: 217.170.197.88
        port: ${{secrets.SERVER_PORT}}
        username: ${{secrets.SERVER_USERNAME}}
        password: ${{secrets.SERVER_PASSWORD}}
        local_folder: ./backend/
        remote_folder: /var/www/eksempler.no/solvann/backend/
        cleanup: false
        exclude: '["tests/**", "node_modules/**"]'

  deploy-frontend:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: frontend
        path: frontend
    - name: Deploy frontend
      uses: sand4rt/ftp-deployer@v1.7
      with:
        sftp: true
        host: 217.170.197.88
        port: ${{secrets.SERVER_PORT}}
        username: ${{secrets.SERVER_USERNAME}}
        password: ${{secrets.SERVER_PASSWORD}}
        local_folder: ./frontend/
        remote_folder: /var/www/eksempler.no/solvann/frontend/
        cleanup: false
        exclude: '["tests/**", "node_modules/**"]'
