# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Compile Project

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]
    paths: [ "frontend/**", "backend/**" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        SOLVANN_USERNAME: ${{secrets.SOLVANN_USERNAME}}
        SOLVANN_PASSWORD: ${{secrets.SOLVANN_PASSWORD}}
  
  build-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test