name: Deploy

on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/**", "backend/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        SOLVANN_USERNAME: ${{secrets.SOLVANN_USERNAME}}
        SOLVANN_PASSWORD: ${{secrets.SOLVANN_PASSWORD}}
